#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_mixer.h>
#include <SDL2/SDL_ttf.h>
#include <bits/stdc++.h>
#include <string>
#include <math.h>
#include <map>

using namespace std;

typedef SDL_Texture G_Texture;
typedef SDL_Rect G_Rect;
typedef TTF_Font G_Font;
typedef Mix_Music G_Music;
typedef Mix_Chunk G_Sound;



#define G_Keyboard event.key.keysym.sym
#define G_Mouse event.button.button

#define G_motion event.motion
#define G_motion event.motion



enum
{
	GK_UNKNOWN = 0,

	GK_RETURN = '\r',
	GK_ESCAPE = '\033',
	GK_BACKSPACE = '\b',
	GK_TAB = '\t',
	GK_SPACE = ' ',
	GK_EXCLAIM = '!',
	GK_QUOTEDBL = '"',
	GK_HASH = '#',
	GK_PERCENT = '%',
	GK_DOLLAR = '$',
	GK_AMPERSAND = '&',
	GK_QUOTE = '\'',
	GK_LEFTPAREN = '(',
	GK_RIGHTPAREN = ')',
	GK_ASTERISK = '*',
	GK_PLUS = '+',
	GK_COMMA = ',',
	GK_MINUS = '-',
	GK_PERIOD = '.',
	GK_SLASH = '/',
	GK_0 = '0',
	GK_1 = '1',
	GK_2 = '2',
	GK_3 = '3',
	GK_4 = '4',
	GK_5 = '5',
	GK_6 = '6',
	GK_7 = '7',
	GK_8 = '8',
	GK_9 = '9',
	GK_COLON = ':',
	GK_SEMICOLON = ';',
	GK_LESS = '<',
	GK_EQUALS = '=',
	GK_GREATER = '>',
	GK_QUESTION = '?',
	GK_AT = '@',
	/*
	Skip uppercase letters
	*/
	GK_LEFTBRACKET = '[',
	GK_BACKSLASH = '\\',
	GK_RIGHTBRACKET = ']',
	GK_CARET = '^',
	GK_UNDERSCORE = '_',
	GK_BACKQUOTE = '`',
	GK_a = 'a',
	GK_b = 'b',
	GK_c = 'c',
	GK_d = 'd',
	GK_e = 'e',
	GK_f = 'f',
	GK_g = 'g',
	GK_h = 'h',
	GK_i = 'i',
	GK_j = 'j',
	GK_k = 'k',
	GK_l = 'l',
	GK_m = 'm',
	GK_n = 'n',
	GK_o = 'o',
	GK_p = 'p',
	GK_q = 'q',
	GK_r = 'r',
	GK_s = 's',
	GK_t = 't',
	GK_u = 'u',
	GK_v = 'v',
	GK_w = 'w',
	GK_x = 'x',
	GK_y = 'y',
	GK_z = 'z',

	GK_CAPSLOCK = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CAPSLOCK),

	GK_F1 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F1),
	GK_F2 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F2),
	GK_F3 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F3),
	GK_F4 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F4),
	GK_F5 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F5),
	GK_F6 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F6),
	GK_F7 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F7),
	GK_F8 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F8),
	GK_F9 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F9),
	GK_F10 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F10),
	GK_F11 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F11),
	GK_F12 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F12),

	GK_PRINTSCREEN = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRINTSCREEN),
	GK_SCROLLLOCK = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SCROLLLOCK),
	GK_PAUSE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAUSE),
	GK_INSERT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_INSERT),
	GK_HOME = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HOME),
	GK_PAGEUP = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEUP),
	GK_DELETE = '\177',
	GK_END = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_END),
	GK_PAGEDOWN = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEDOWN),
	GK_RIGHT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RIGHT),
	GK_LEFT = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LEFT),
	GK_DOWN = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DOWN),
	GK_UP = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UP),

	GK_NUMLOCKCLEAR = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_NUMLOCKCLEAR),
	GK_KP_DIVIDE = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DIVIDE),
	GK_KP_MULTIPLY = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MULTIPLY),
	GK_KP_MINUS = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MINUS),
	GK_KP_PLUS = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUS),
	GK_KP_ENTER = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_ENTER),
	GK_KP_1 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_1),
	GK_KP_2 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_2),
	GK_KP_3 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_3),
	GK_KP_4 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_4),
	GK_KP_5 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_5),
	GK_KP_6 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_6),
	GK_KP_7 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_7),
	GK_KP_8 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_8),
	GK_KP_9 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_9),
	GK_KP_0 = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_0),
	GK_KP_PERIOD = SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERIOD),